export const ORDER_STATUSES = [
  { value: "PENDING", label: "Pending", color: "warning" },
  { value: "CONFIRMED", label: "Confirmed", color: "info" },
  { value: "PROCESSING", label: "Processing", color: "info" },
  { value: "SHIPPED", label: "Shipped", color: "neutral" },
  { value: "DELIVERED", label: "Delivered", color: "success" },
  { value: "CANCELLED", label: "Cancelled", color: "error" },
  { value: "RETURNED", label: "Returned", color: "neutral" },
  { value: "REFUNDED", label: "Refunded", color: "neutral" },
] as const;

export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
] as const;

export const PRODUCT_CATEGORIES = [
  { name: "Women's Clothing", slug: "womens-clothing" },
  { name: "Men's Clothing", slug: "mens-clothing" },
  { name: "Kids Fashion", slug: "kids-fashion" },
  { name: "Ethnic Wear", slug: "ethnic-wear" },
  { name: "Western Wear", slug: "western-wear" },
  { name: "Accessories", slug: "accessories" },
  { name: "Footwear", slug: "footwear" },
  { name: "Bags", slug: "bags" },
  { name: "Jewellery", slug: "jewellery" },
  { name: "Activewear", slug: "activewear" },
] as const;
